console.log("Morning!");
console.log(100);
console.log('A');
console.log(98.25);
console.log(5*4);
console.log("Morning " + "EUREKA");
const x = 100;
console.log(x);
console.error('Alert');
console.warn('Warning');